### ISSUE TITLE
Own latitude & longitude

### ISSUE THREAD

**Issue by frejnielsen** [Coronon/FMFriends#2]
Hi Coronon

Thanks for creating this awesome API, I really enjoy it :)

I have a question regarding my own longitude and latitude, which I can't seem to find in the results.  Is this data no available?

The reason i'm asking is that it seems to be available in the app, so I was wondering if it's also available here?

Thanks again for this API :)

**Comment by Coronon** [comment]
Hi, I'm very sorry for the late reply, I'm quite busy at the moment, but I will have a look into it next weekend.
You are right, there should be a way to get your own position.
Its just quite hard to get the right data through analyzing the http traffic,

yours Coronon

**Comment by Coronon** [comment]
https://github.com/Coronon/FMFriends/pull/3

**Comment by Coronon** [comment]
https://github.com/Coronon/FMFriends/pull/3

**Comment by Coronon** [comment]
Btw. you can actually add yourself as a friend using your phone number if you are sharing over email or email when sharing over phone number
